env:
  TUBULAR_AWS_DEVELOPMENT_ACCOUNT_ID: "206187504452"
steps:
  - label: testing
    command:
    - echo "HI"
    - go build -o main .
    - zip deployment.zip main
    - tubular artifact deployment.zip
    - tubular activate

